[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  identifier = "envelope"
  pre = "envelope"
  name = "Contact"
  pageRef = "contact"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ayodhya16"
  weight = 40

[[main]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/maheshbabu168"
  weight = 50

[[main]]
  identifier = "yt"
  pre = "youtube"
  url = "https://www.youtube.com/@maheshbabu2221"
  weight = 60

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/ayodhya-mahesh-babu-387845254/"
  weight = 70

[[footer]]
  name = "Contact me"
  pre = "envelope"
  pageRef = "contact"
  weight = 10

[[footer]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/ayodhya16"
  weight = 20


[[footer]]
  identifier = "twitter"
  pre = "x-twitter"
  url = "https://x.com/maheshbabu168"
  weight = 20

[[footer]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/ayodhya-mahesh-babu-387845254/"
  weight = 30

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20