name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo with submodules
      - uses: actions/checkout@v4
        with:
          submodules: true

      # 2. Setup Hugo
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.151.0'
          extended: true

      # 3. Build Hugo site from repo root
      - name: Build Hugo site
        run: hugo --minify -D

      # 4. Upload public folder as artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      # 5. Deploy to GitHub Pages
      - uses: actions/deploy-pages@v4
        id: deployment
