name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Build Hugo site
      - name: Build
        run: hugo --minify

      # Upload the public folder as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
